Добавляет доку с описанием деплоя
Y-Doka/platform pull request #106
Opened 2021-05-02 12:58 UTC by nlopin

2021-05-02 12:59 UTC, nlopin commented on README.md
> +Проект [собирается через GitHub Actions](./docs/deploy.md) и публикуется в Netlfiy.
я не уверен, что нужно это добавлять в README, но иначе как мне кажется никто не найдет описание

2021-05-02 14:19 UTC, furtivite requested changes

2021-05-02 14:19 UTC, furtivite commented on README.md
> +Проект [собирается через GitHub Actions](./docs/deploy.md) и публикуется в Netlfiy.
Мне кажется, что это стоит перенести в раздел Деплой Доки. Там он более к месту.

2021-05-02 15:27 UTC, pepelsbey commented on docs/deploy.md
> +
```suggestion
Дока хостится на [Netlify](https://www.netlify.com/) как набор статических файлов.
```

Кажется можно проще и точнее :)

2021-05-02 15:27 UTC, pepelsbey commented on docs/deploy.md
> +
```suggestion
Автоматически, при слиянии пулреквеста в ветку `main` в репозитории `content` или `platform`.
```

2021-05-02 15:27 UTC, pepelsbey commented on docs/deploy.md
> +1. Отправить папку со сборкой в Netlify
```suggestion
Проект собирается с помощью [GitHub Actions](https://docs.github.com/en/actions).

В каждом репозитории описан свой воркфлоу для сборки, но они идентичны по содержанию:

- [Воркфлоу контента](https://github.com/Y-Doka/content/blob/main/.github/workflows/netlify-deploy.yml)
- [Воркфлоу платформы](https://github.com/Y-Doka/platform/blob/main/.github/workflows/netlify-deploy.yml)

Сборка состоит из пяти этапов:

1. Скачать свежие версии контента и платформы
1. Установить зависимости
1. Подключить статьи к платформе
1. Собрать проект
1. Отправить папку со сборкой в Netlify
```

Добавляет ссылку на экшены, будет полезно. Нормализует и русифицирует контент, платформу, воркфлоу.

2021-05-02 15:27 UTC, pepelsbey commented on README.md
> +Проект [собирается через GitHub Actions](./docs/deploy.md) и публикуется в Netlfiy.
Полезно ссылаться на документацию из ридми, я бы просто ссылку поставил лучше:

```suggestion
Проект собирается с помощью GitHub Actions и хостится в Netlfiy, читайте [подробнее про деплой](./docs/deploy.md).
```

2021-05-02 20:02 UTC, nlopin commented on docs/deploy.md
> +1. Отправить папку со сборкой в Netlify
а зачем переводить? я тут скорее следовал нашим соглашениям по контенту, хотя это и не контент

2021-05-03 08:10 UTC, furtivite approved these changes

2021-05-03 11:13 UTC, pepelsbey commented on docs/deploy.md
> +1. Отправить папку со сборкой в Netlify
Перевод здесь чтобы более простым языком говорить. Мне кажется, не обязательно каждый раз писать «код» `platform` или `content` (который даже не код), если можно говорить платформа и контент.

2021-05-03 14:35 UTC, nlopin commented on docs/deploy.md
> +1. Отправить папку со сборкой в Netlify
мне было бы проще читать workflow, а не воркфлоу, но хрен с ним, это мелочи

2021-05-03 14:36 UTC, merged