Правит пути до демок
Y-Doka/platform pull request #117
Opened 2021-05-06 14:45 UTC by furtivite

2021-05-06 15:33 UTC, pepelsbey requested changes
Я бы убрал отсюда изменения в зависимостях

2021-05-06 22:00 UTC, nlopin commented on .eleventy.js
> +      content = content.replace(iframePath, (math) => {
кажется можно обойтись без функции вторым параметром и оставить просто строку:

```
content = content.replace(iframePath, 'src="./demos/')
```

2021-05-07 02:39 UTC, furtivite commented on .eleventy.js
> +      content = content.replace(iframePath, (math) => {
> кажется можно обойтись без функции вторым параметром и оставить просто строку:
> 
> ```
> content = content.replace(iframePath, 'src="./demos/')
> ```

Да, так выглядит значительно приятнее, согласен.

2021-05-07 02:44 UTC, furtivite commented on .eleventy.js
> +  config.addTransform('fix-demos', (content, outputPath) => {
Попробовал описать.

2021-05-07 07:54 UTC, nlopin commented on .eleventy.js
> +  config.addTransform('fix-demos', (content, outputPath) => {
О, это интересный кейс. Думаю, что раз у нас всё на русском, то и комменты стоит на русском писать. 

Извини, что сразу не сказал. На английском хороо написал

2021-05-07 08:17 UTC, pepelsbey commented on .eleventy.js
> +  // After executing {% include "practices.njk"%}, the paths in the <iframe> with the demo are broken, because in the content these paths are specified relatively, and the {% include %} function take
```suggestion
  // Правит пути к демкам внутри советов
```
Кажется можно проще…

2021-05-07 10:32 UTC, pepelsbey requested changes
В пулреквесте всё ещё есть изменения в пакетах (

2021-05-07 10:32 UTC, pepelsbey commented on .eleventy.js
> +  config.addTransform('fix-demos', (content, outputPath) => {
```suggestion
  config.addTransform('fixDemos', (content, outputPath) => {
```
У нас другой кейс внутри JS, был неправ

2021-05-07 14:35 UTC, pepelsbey approved these changes

2021-05-07 22:30 UTC, nlopin commented
Развернул комментарий, а то «правит пути в демках» даёт слишком мало контекста

2021-05-07 22:31 UTC, merged