Обновляет архитектуру
Y-Doka/platform pull request #154
Opened 2021-05-27 13:48 UTC by furtivite

<img width="1800" alt="Итоговая версия" src="https://user-images.githubusercontent.com/50330458/119828020-72b16400-bf02-11eb-9b10-742d83ceae8b.png">

Было:
- Архитектура «матрёшка», где было много зависимых слоёв, которые встраивались друг в друга. 
- Из-за наличия множества встраиваний через `{{ content | safe }}` происходила деформация контента и было невозможно встроить необходимые плагины (например Images #3)
- Если необходимо создать страницу с боковой панелью, нужно дописывать недостающие модули в `*.njk`-файлах для каждой конкретной страницы.

Сделано:
- Упрощённая система слоёв, где при создании нового контента выбираются нужные независимые элементы.
- Организованы реиспользуемые блоки в качестве инклюдов.
- Вынесена настройка стандартного лейаута в конфиг.

2021-05-27 17:05 UTC, pepelsbey reviewed
Я не очень понимаю, зачем заводить систему дефолтных шаблонов, класть это в переменную окружения и писать документацию. Всё ещё 10 раз поменяется, давайте делать проще и быстрее.

2021-05-27 17:07 UTC, pepelsbey commented on docs/layouts.md
> +- `<div class="base__container"></div>` — для ограничения максимальной ширины контента
Пожалуйста, давай перестанем верстать, это пока не нужно.

2021-05-31 16:39 UTC, pepelsbey requested changes
Давай упростим решение:

1. Заведём новую систему шаблонов
2. Расставим шаблоны по нужным метам

И всё :) Переменные, экспорты, вёрстку, документацию давай уберём.

И двинемся дальше к самой задаче с картинками.

2021-06-01 10:37 UTC, pepelsbey approved these changes

2021-06-01 10:38 UTC, pepelsbey commented
@furtivite немного отрефакторил тоже:

- ul/logo.njk — blocks/logo.njk
- tech/head.njk — meta.njk

Так более последовательно. Давай мёржить, если ок.

2021-06-01 10:40 UTC, furtivite commented
Надо замержить [пиар в другом репозиториии](https://github.com/Y-Doka/content/pull/722) сразу, как только будет возможность.

2021-06-01 10:40 UTC, merged