Первые правки шаблонов
Y-Doka/platform pull request #18
Opened 2021-03-19 10:30 UTC by furtivite

- Переименовывает page в base
    Это сделано для разделения сущностей. Всё глобальное будет подключаться сразу к base. От него будем передвигаться дальше. 
- Переносит шрифты и добавляет лицензии
    Шрифты теперь разложены по своим папкам и у каждого добавлен файл лицензии. Лицензия — это очень важно, она должна быть у каждого вендорского файла. Поэтому произошло перемещение по папкам. 
- Вводит понятие класса для темплейта
    Это упростит редактирование страницы, потому что пропадает лишняя обёртка. 
    Класс темплейта задаётся в мете у страницы и добавляется прямо в `<body>`, что увеличивает привязку к БЭМ, и требованиям материнской организации. 
- Создаёт UI элементы
    Перенёс логотип в UI-элемент внутри инклюдов. Все повторяющиеся элементы должны лежать в одном месте, чтобы увеличить возможность их переиспользования. 
    В случае, если у нас такой элемент потребуется изменить, мы сможем сделать это в одном месте, а не бегать по сайту и искать, где и что забыли поменять.

2021-03-19 17:31 UTC, pepelsbey requested changes

2021-03-19 17:31 UTC, pepelsbey commented on src/layouts/base.njk
> +  <body class="base__body {% if templateClass %}{{ templateClass }}{% endif %}">
Я бы не стал вводить классы на всякий случай. Плюс предлагаю лучше действовать ближе к БЭМу и модифицировать не от контекста, а модификаторами на нужных блоках. То есть нет проблемы заводить ключи в шаблонах (когда это будет нужно), но не стоит их выводить как классы.

2021-03-19 17:31 UTC, pepelsbey commented on src/styles/index.css
> +@import 'fonts/roboto/roboto-mono.css';
Нужно ещё апнуть пути к файлам шрифтов тогда, если группируем по папкам.

`../../fonts/roboto-mono/italic.woff2` — `../../../fonts/roboto-mono/italic.woff2`

2021-03-19 17:31 UTC, pepelsbey commented on src/pages/index.njk
> +  {% include "../includes/ui/logo.njk" %}
```suggestion
  {% include "ui/logo.njk" %}
```
Можно не указывать пути, он знает где искать инклюды

2021-03-23 07:15 UTC, furtivite commented on src/layouts/base.njk
> +  <body class="base__body {% if templateClass %}{{ templateClass }}{% endif %}">
Смотри, вот тут предлагается использовать классический БЭМ-микс, когда на одном DOM-элементе висят несколько классов, относящихся к разным сущностям. Тут есть некий `templateClass`-блок который определяет поведение элементов внутри себя, но при этом мы не используем излишнюю вложенность элементов.

2021-03-23 07:19 UTC, furtivite commented on src/pages/index.njk
> +  {% include "../includes/ui/logo.njk" %}
Да, точно, забыл об этом.

2021-03-23 07:44 UTC, furtivite commented on src/layouts/base.njk
> +  <body class="base__body {% if templateClass %}{{ templateClass }}{% endif %}">
Договорились, что это изменение откатывается и вносится отдельным пиаром.

2021-03-23 07:59 UTC, furtivite commented
Про классы темплейтов [вынесено в дискуссии](https://github.com/Y-Doka/platform/discussions/25).

2021-03-23 08:32 UTC, pepelsbey approved these changes

2021-03-23 15:33 UTC, nlopin approved these changes

2021-03-24 07:54 UTC, merged