Правит блоки и добавляет асайд и страницу с ним
Y-Doka/platform pull request #27
Opened 2021-03-25 09:13 UTC by furtivite

Всё переиспользуемое перенесено в инклюды.

2021-03-29 10:50 UTC, pepelsbey requested changes

2021-03-29 10:50 UTC, pepelsbey commented on src/includes/aside.njk
> +    <button class="aside__arrow-btn" title="Скрыть боковую навигацию"></button>
```suggestion
    <button class="aside__arrow-btn" type="button" aria-label="Скрыть навигацию"></button>
```

2021-03-29 10:50 UTC, pepelsbey commented on src/includes/footer.njk
> +      Присоединяйся&nbsp;<br class="footer__break">
```suggestion
      Присоединяйся<br class="footer__break">
```
Непонятно, зачем здесь пробел?

2021-03-29 10:50 UTC, pepelsbey commented on src/scripts/modules/aside.js
> +const asidePage = document.querySelector(".aside-page");
```suggestion
const asidePage = document.querySelector(".aside-page")
```

2021-03-29 11:36 UTC, furtivite commented on src/includes/footer.njk
> +      Присоединяйся&nbsp;<br class="footer__break">
У меня в огнелисе без пробела следующее слово иногда прилипает. В safari пару раз такое же замечал. 

![Снимок экрана 2021-03-29 в 14 35 19](https://user-images.githubusercontent.com/50330458/112831012-ff26de00-909b-11eb-8e06-bd536dbb3b6b.png)

Потому добавил пробел.

2021-03-29 11:37 UTC, furtivite commented on src/styles/index.css
> +@import 'pages/aside-page.css';
Надо со всеми обсудить, но если мы не выделим, потом можем и запутаться. Хотя технически, всё есть блок, и понятно, зачем он нужен. Просто некоторые лучше всегда держать выше.

2021-03-29 11:39 UTC, pepelsbey commented on src/styles/index.css
> +@import 'pages/aside-page.css';
Давай всё же делать классический БЭМ, где есть блоки и всё. А выделять их среди остальных можно с помощью префикса **page-block.css**, например.

2021-03-29 11:46 UTC, furtivite commented on src/styles/index.css
> +@import 'pages/aside-page.css';
Да, давай такой вариант.

2021-03-29 11:51 UTC, pepelsbey commented
Упростил футер. И давай пока верстать вообще не будем и сосредоточимся на шаблонах и данных.

2021-04-06 13:56 UTC, furtivite commented
Пока работаю над пул-реквестом. Собираю коллекции

2021-04-06 15:38 UTC, furtivite commented
В файл `.eleventy.js` добавлено автоматическое создание коллекций, для элементов в папках.

2021-04-06 16:18 UTC, furtivite commented
Есть идея by @igsekor : записать стандартные файлы платформы в константы, потом проходиться при сборке через `fs` по папкам, и те, которых нет в константе добавлять в массив для генерации файла. Это упростит переезд для других пользователей.

2021-04-06 21:21 UTC, nlopin commented on .eleventy.js
> +  config.addNunjucksShortcode('getInfo', (file) => {
этот шорткод нигде не используется. зачем он нужен?

У Игоря это был способ показать, что джейсон инклудится. Нам он кажется не нужен

2021-04-06 21:21 UTC, nlopin commented on .eleventy.js
> +const COMANDS = ['html', 'css', 'js', 'tools']
Может `SECTIONS`?

2021-04-06 21:21 UTC, nlopin commented on .eleventy.js
> +  ['articles', 'doka',].forEach((el) => {
Я бы тоже вынес в константу, как и в коде выше

2021-04-06 21:21 UTC, nlopin commented on .eleventy.js
> +      return collectionApi.getFilteredByGlob(`src/${el}/**`);
не уверен, что пути будут норм работать на винде. Может стоит воспользоваться [модулем path](https://nodejs.org/api/path.html)

2021-04-06 21:21 UTC, nlopin commented on common.json
> +{
где этот json используется? я вижу, что он добавлен, но нигде в коде нет упоминаний. Он автоматически применяется eleventy?

2021-04-06 21:23 UTC, nlopin commented on make-links.js
> +const CONTENT_FOLDERS = ['html', 'css', 'js', 'tools']
Мы дублируем название папок в куче мест. Давай вынесем в одно место куда-нибудь.

Понадобится добавить новую секцию, придется несколько файлов менять

2021-04-07 02:45 UTC, furtivite commented on .eleventy.js
> +const COMANDS = ['html', 'css', 'js', 'tools']
У нас нет массивов капсом, это остатки того, что родилось во время разработки, чтобы глазом не потерялось.
Переименовал в `articleSections`

2021-04-07 02:45 UTC, furtivite commented on .eleventy.js
> +  ['articles', 'doka',].forEach((el) => {
Вынес как `articleFormats`

2021-04-07 02:48 UTC, furtivite commented on .eleventy.js
> +      return collectionApi.getFilteredByGlob(`src/${el}/**`);
модулем path стоит воспользоваться, но у меня возникает «проблема несмёрженных пиаров» поэтому я бы принял пока так, и завёл issue на рефакторинг кода.

на windows всё работает, проверено

![2021-04-07_05-34-03](https://user-images.githubusercontent.com/50330458/113803145-9bb84280-9764-11eb-9ba2-38bdd63f9ef2.png)

2021-04-07 02:48 UTC, furtivite commented on common.json
> +{
не используется, он остался от решения Игоря, я не заметил, спасибо. Удалил.

2021-04-07 02:51 UTC, furtivite commented on make-links.js
> +const CONTENT_FOLDERS = ['html', 'css', 'js', 'tools']
Согласен, тут нужен интерфейс, чтобы пользователь при первой миграции мог указать этот список файлов где-то, а затем хранить этот массив в отдельном месте и тащить его во все папки, где надо.

2021-04-07 02:57 UTC, furtivite commented on .eleventy.js
> +  config.addNunjucksShortcode('getInfo', (file) => {
удалил, действительно, забыл про него.

2021-04-07 14:41 UTC, nlopin approved these changes

2021-04-08 08:55 UTC, furtivite commented on src/styles/pages/aside-page.css
> +.aside-page_hidden-aside {
@pepelsbey может стили эти поправим чуть позже, когда будем делать стили? Я себе пометил, что надо поправить. Зато запуститься быстрее сможем.

2021-04-08 10:56 UTC, pepelsbey commented on src/styles/pages/aside-page.css
> +.aside-page_hidden-aside {
Давай тогда просто не писать стили :) И будет быстрее.

2021-04-08 10:57 UTC, pepelsbey approved these changes

2021-04-09 06:38 UTC, merged