Добавляет первый вариант ридми
Y-Doka/platform pull request #34
Opened 2021-04-02 12:40 UTC by furtivite

У нас нет ридми — это непорядок, и усложняет разработку. Например, новые контрибьюторы смогут понять, как запустить локальную версию Доки и начать с ней работать и видеть готовые статьи.

2021-04-02 12:49 UTC, pepelsbey commented on README.md
> +Этот репозиторий содержит платформу для сайта «[Дока](y-doka.site/)», которая собирает статьи из [отдельного репозитория](github.com/y-Doka/platform).
```suggestion
Этот репозиторий содержит платформу для сайта «[Дока](https://y-doka.site/)», которая собирает статьи из [отдельного репозитория](https://github.com/y-doka/platform).
```

2021-04-02 12:51 UTC, pepelsbey commented on README.md
> +Для работы с платформой вам потребуется [Node.js (v14.16.0 LTS)](https://nodejs.org/en/) и NPM (v. 7.7.0).
```suggestion
Для работы с платформой вам потребуется [Node.js v14+](https://nodejs.org/en/) и npm v7+.
```

2021-04-02 12:58 UTC, furtivite commented on README.md
> +Этот репозиторий содержит платформу для сайта «[Дока](y-doka.site/)», которая собирает статьи из [отдельного репозитория](github.com/y-Doka/platform).
Надо по тому же принципу поправить тогда и в content. Ок

2021-04-03 21:52 UTC, nlopin requested changes

2021-04-03 21:52 UTC, nlopin commented on README.md
> +Этот репозиторий содержит платформу для сайта «[Дока](y-doka.site/)», которая собирает статьи из [отдельного репозитория](github.com/y-Doka/platform).
только отдельный репозиторий называется `content`, а не `platform`, как в ссылке

2021-04-05 12:54 UTC, tachisis requested changes

2021-04-05 12:54 UTC, tachisis commented on README.md
> +Дока — это место, в котором мы с огоньком перекапываем документацию по веб-разработке. Наша цель сделать ее практичной, понятной и не унылой.
Мне не очень нравится это «Дока — это место» и «перекапывание с огоньком», и я подумываю переформулировать это введение в том числе и в репе с контентом. В одном из наших файлов была такая формулировка: «Дока — это добрая энциклопедия для веб-разработчиков». К этому можно добавить: «Наша цель — сделать документацию по веб-разработке практичной, понятной и не унылой».

2021-04-05 12:54 UTC, tachisis commented on README.md
> +Этот репозиторий содержит платформу для сайта «[Дока](https://y-doka.site/)», которая собирает статьи из [отдельного репозитория](https://github.com/y-doka/content).
```suggestion
Этот репозиторий содержит платформу для сайта «[Дока](https://y-doka.site/)». Платформа собирает статьи из [отдельного репозитория](https://github.com/y-doka/content).
```

2021-04-05 12:54 UTC, tachisis commented on README.md
> +Сайт «Доки» работает на базе [Eleventy](https://www.11ty.dev), которая собирает статьи — Markdown-файлы в HTML-страницы для вашего браузера при помощи Nunjucks-темплейтов.
```suggestion
Сайт «Доки» работает на базе [Eleventy](https://www.11ty.dev). При помощи Nunjucks-темплейтов Eleventy превращает статьи в формате Markdown в HTML-страницы.
```

2021-04-05 12:54 UTC, tachisis commented on README.md
> +Чтобы запустить свою локальную версию Доки нужно:
```suggestion
Чтобы запустить Доку локально, нужно:
```

2021-04-05 12:54 UTC, tachisis commented on README.md
> +1. запустить скрипт кросслинковки командой `node make-links.js` у вас в папке `./src` появятся нужные папки с контентом из соседнего репозитория
```suggestion
1. запустить скрипт кросслинковки командой `node make-links.js`: у вас в папке `./src` появятся нужные папки с контентом из соседнего репозитория
```

2021-04-05 22:11 UTC, nlopin requested changes

2021-04-05 22:11 UTC, nlopin commented on README.md
> +1. скачать репозитории с контентом и платформой в одну папку
мы проговаривали, что этот шаг опциональный, так как у нас будут тестовые страницы. Подключать контент нужно, только если очень хочется

поэтому и третий шаг тоже отпадает

Это стоит в отдельный файл вынести, предлагаю пока оставить только 
1. `npm i` для установки зависимостей
2. `npm start` для старта

2021-04-06 08:27 UTC, furtivite commented on README.md
> +1. скачать репозитории с контентом и платформой в одну папку
Согласен, давай вынесем в отдельный файл и дадим ссылку. Обновлю.

2021-04-06 21:13 UTC, nlopin approved these changes

2021-04-06 21:18 UTC, pepelsbey approved these changes

2021-04-07 05:36 UTC, furtivite commented on README.md
> +Дока — это место, в котором мы с огоньком перекапываем документацию по веб-разработке. Наша цель сделать ее практичной, понятной и не унылой.
Поставил этот вариант, потом можно поправить окончательно в отдельном ишью.

2021-04-07 09:24 UTC, tachisis requested changes

2021-04-07 09:24 UTC, tachisis commented on README.md
> +Больше вариантом локального запуска Доки [по ссылке](docs/how-to-run.md)
```suggestion
Больше вариантов локального запуска Доки — [в руководстве по запуску](docs/how-to-run.md)
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. скачать репозиторий
```suggestion
1. Скачать репозиторий.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. установить зависимости командой `npm i`
```suggestion
1. Установить зависимости командой `npm i`.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. запустить локальный веб-сервер командой `npm start`
```suggestion
1. Запустить локальный веб-сервер командой `npm start`.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. скачать репозитории с контентом и платформой в одну папку
```suggestion
1. Скачать репозитории с контентом и платформой в одну папку.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. установить зависимости командой `npm i`
```suggestion
1. Установить зависимости командой `npm i`.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. запустить скрипт кросслинковки командой `node make-links.js` у вас в папке `./src` появятся нужные папки с контентом из соседнего репозитория
```suggestion
1. Запустить скрипт кросслинковки командой `node make-links.js`: у вас в папке `./src` появятся нужные папки с контентом из соседнего репозитория.
```

2021-04-07 09:24 UTC, tachisis commented on docs/how-to-run.md
> +1. запустить локальный веб-сервер командой `npm start`
```suggestion
1. Запустить локальный веб-сервер командой `npm start`.
```

2021-04-07 09:46 UTC, furtivite commented on docs/how-to-run.md
> +1. скачать репозитории с контентом и платформой в одну папку
Мы точно хотим после каждого пункта ставить точку? [Вот тут](https://github.com/Y-Doka/content/tree/edit/298-author-docs#станьте-автором) в первом списке точек нет.

2021-04-07 14:32 UTC, tachisis commented on docs/how-to-run.md
> +1. скачать репозитории с контентом и платформой в одну папку
Хотим и хотим везде :)

2021-04-07 14:45 UTC, tachisis approved these changes

2021-04-07 14:47 UTC, merged