Добавляет блок с практиками
Y-Doka/platform pull request #56
Opened 2021-04-16 14:57 UTC by furtivite

Добавил мнения авторов на основании урла статьи, и поскольку иначе надо было обосновать блок «В работе», а у меня не получилось убрать этот блок, если мнений авторов нет, сделал призыв такие мнения оставить. Это позволит развивать проект.

2021-04-16 15:17 UTC, pepelsbey reviewed
Хочется как-то более понятно получать части пути, может @nlopin подскажет?

```
slice(page.url.length + 9)
page.inputPath.slice(6, -8)
```

А то магические числа (

2021-04-16 16:09 UTC, furtivite commented
> Хочется как-то более понятно получать части пути, может @nlopin подскажет?
> 
> ```
> slice(page.url.length + 9)
> page.inputPath.slice(6, -8)
> ```
> 
> А то магические числа и кажется, что может сломаться (

6 - это `./src/` - который появляется в платформе, но отсутствует в контенте
-8 - это `practice` - соответственно папка с практиками

Можно сделать так: 

В начале файла заводим две переменные, как `{% set defaultPath = './src/' %}` - он от проекта к проекту меняться не будет, и `{% set practicePath = 'practice' %}`, который можно передавать из глобальных переменных, как блок в работе...

2021-04-18 21:45 UTC, nlopin requested changes
Я оставил комментарий в #57 о том, как избавиться от магических чисел, но сейчас понимаю, что нам нужен не только другой метод, но и немного семантики. 

Две идеи:
* считать свойство `practiceAuthor` (или просто `author`) и `contentRepoPath` через [`dataComputed`](https://www.11ty.dev/docs/data-computed/) в `src`. Так в шаблонах вообще не будет логики, а только использование свойств страницы
* вариант похуже — добавить [фильтры](https://www.11ty.dev/docs/filters/), чтобы делать хотя бы так `{{ page.inputPath | githubLinkToContent }}`

2021-04-18 21:45 UTC, nlopin commented on src/includes/practices.njk
> +    {% if practice.filePathStem.indexOf(page.url) %}
зачем такое условие, если мы всегда его пропускаем? может использовать `includes` или `startsWith`?

2021-04-19 08:24 UTC, furtivite commented on src/includes/practices.njk
> +    {% if practice.filePathStem.indexOf(page.url) %}
@nlopin `dataComputed` требует нахождения всех файлов, которые он обрабатывает в одной папке, и мы снова возвращаемся к вопросу о необходимости такой папки, или созданию таких файлов в каждой из секций, потому что иначе она будет обрабатывать все файлы из `src`, а не только секционные.

2021-04-19 15:51 UTC, furtivite commented
Немножко избавился от slice

2021-04-19 16:20 UTC, pepelsbey commented on src/includes/practices.njk
> +        <h3 class="practices__author">{{ '@' + author }}</h3>
```suggestion
        <h3 class="practices__author">@{{ author }}</h3>
```
Меньше программирования :)

2021-04-19 16:25 UTC, pepelsbey commented on src/includes/practices.njk
> +    <p>Вы можете помочь проекту, если напишите, как применяете элемент, свойство или подход, который мы описали в статье, на практике. <a href="https://github.com/Y-Doka/content/tree/master/{{ page.i
```suggestion
    <p>Вы можете помочь проекту, если напишите, как применяете элемент, свойство или подход, который мы описали в статье, на практике. <a href="https://github.com/Y-Doka/content/tree/master/{{ page.inputPath.slice(6, -8) }}">Начать на Github.</a></p>
```

Тут ещё slice остался. И эта ссылка пока не очень помогает добавлять практические советы. Откроется файл, а дальше? Тут лучше ссылать на документацию по практике, которой у нас пока нет. Может откажемся от этой фичи, пока она у нас не готова? И сконвертируем в задачу на будущее.

2021-04-19 16:44 UTC, furtivite commented on src/includes/practices.njk
> +    <p>Вы можете помочь проекту, если напишите, как применяете элемент, свойство или подход, который мы описали в статье, на практике. <a href="https://github.com/Y-Doka/content/tree/master/{{ page.i
Убрал `slice`. Пока ссылка ведёт на папку статьи, где можно создать папку `practice`, если её нет, или файл нужны, если он есть. Этот блок нужен, потому что, если практик нет, то заголовок «В работе» выводится, но не ясно, зачем он там. А так более понятно.

2021-04-19 20:11 UTC, pepelsbey commented on src/includes/practices.njk
> +    <p>Вы можете помочь проекту, если напишите, как применяете элемент, свойство или подход, который мы описали в статье, на практике. <a href="https://github.com/Y-Doka/content/tree/master/{{ page.i
Так может нам проверить, есть ли практики и не выводить заголовок, если их нет? Просто мы даже не обсудили с лидами, хотим ли мы такую механику. У меня чувство, что она следует из кода :) Давай пока выведем то, что у нас есть.

2021-04-19 21:39 UTC, pepelsbey commented
@nlopin @furtivite я сильно упростил вывод практики с помощью функции-хелпера, которая фильтрует практики текущей страницы. Ну и при выводе обошёлся проще. Как вам такое решение?

2021-04-19 21:42 UTC, pepelsbey commented
Аналогичным образом можно поступать с коллекцией people и в других похожих ситуациях: проверять принадлежность в фильтре.

2021-04-20 08:15 UTC, nlopin commented on .eleventy.js
> +  config.addFilter('filterPractice', (array, page) => {
Фильтр кажется достаточно общим, предлагаю придумать ему менее специфичное имя. Что думаешь о `filterChildrenOf` или `belongsTo`?

В коде получится:

```js
{% set pagePractice = collections.practice | filterChildrenOf(page) %}
{% set pagePractice = collections.practice | belongsTo(page) %}
```

2021-04-20 08:16 UTC, nlopin approved these changes

2021-04-20 08:47 UTC, pepelsbey commented on .eleventy.js
> +  config.addFilter('filterPractice', (array, page) => {
Не подумал про универсальность, круто! Назвал `keepRelatedTo`, лучше передаёт суть.

2021-04-20 08:50 UTC, pepelsbey approved these changes

2021-04-20 08:50 UTC, merged