Добавляет кнопку для редактирования статьи
Y-Doka/platform pull request #57
Opened 2021-04-16 14:58 UTC by furtivite

Добавил вывод блока у заголовка статьи для правок. 
Там надо прокидывать глобальную переменную с названием репозитория, когда у нас такие будут в файле настроек из #53

2021-04-16 15:14 UTC, pepelsbey commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master/{{ page.inputPath.slice(6) }}" target="_blank" title="Редактировать на Github.com">&#9998;</a>
```suggestion
  <a href="https://github.com/Y-Doka/content/blob/master/{{ page.inputPath.slice(6) }}" target="_blank">
    Редактировать на GitHub
  </a>
```

Предлагаю пока явно писать, что это значит, не прятать в тайтле (на таче его нет).

2021-04-17 12:44 UTC, pepelsbey approved these changes

2021-04-18 14:18 UTC, nlopin requested changes

2021-04-18 14:18 UTC, nlopin commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master/{{ page.inputPath.slice(6) }}" target="_blank">
Мне пришлось выкачать ветку, чтобы разобраться, что мы от чего отрезаем. Сейчас код выглядит криптографично. 

Предлагаю альтернативные варианты:
* заменить `slice` на `replace`, чтобы явно показать что выкидываем: `replace("./src/", "")`
* использовать `page.url`, тогда не придётся вообще что-либо заменять. Из минусов — нет гарантии, что когда-либо урлы не разойдутся с файловой системой

2021-04-19 10:58 UTC, pepelsbey commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master/{{ page.inputPath.slice(6) }}" target="_blank">
Давайте сделаем replace, это проще всего и наглядно

2021-04-19 15:11 UTC, furtivite commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master/{{ page.inputPath.slice(6) }}" target="_blank">
Мне наоборот показалось, что `page.url` более визуально понятно.

2021-04-19 15:12 UTC, furtivite commented
1. Убрал слайсы
2. Вывел адрес репозитория с контентом в переменную, чтобы визуально было более понятно, что происходит, при подключении другого контента.

2021-04-19 15:34 UTC, pepelsbey commented on src/layouts/article.njk
> +contentRep: "https://github.com/Y-Doka/content/blob/master"
Мы наверняка захотим использовать этот путь где-нибудь ещё, не только в этом шаблоне. Я бы сейчас оставил как есть, прямо в шаблоне, а потом абстрагируем отдельным делом.

И лок-файл откати, плиз :)

2021-04-19 15:40 UTC, furtivite commented on src/layouts/article.njk
> +contentRep: "https://github.com/Y-Doka/content/blob/master"
Я вообще думал в мету его закинуть, там всё равно хранятся постоянные переменные, но не очень прокидывается.

2021-04-19 16:33 UTC, pepelsbey approved these changes

2021-04-19 16:59 UTC, furtivite commented on src/layouts/article.njk
> +contentRep: "https://github.com/Y-Doka/content/blob/master"
Завёл #58

2021-04-20 08:34 UTC, furtivite commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master{{ page.url }}" target="_blank">
```suggestion
  <a href="{% contentRep %}/blob/master{{ page.url }}" target="_blank">
```

@pepelsbey @nlopin А что если я прокину сюда шорткодом из глобальных переменных адрес репозитория?

2021-04-20 08:36 UTC, furtivite commented on src/layouts/article.njk
> +  <a href="https://github.com/Y-Doka/content/blob/master{{ page.url }}" target="_blank">
```suggestion
  <a href="{% contentRep %}/blob/master{{ page.url }}" target="_blank">
```

@pepelsbey @nlopin А что если я прокину сюда шорткодом из глобальных переменных адрес репозитория? И в случае изменения репозитория с контентом надо будет только в ENV файле поправить?

2021-04-20 09:03 UTC, merged