Добавляет 404 страницу
Y-Doka/platform pull request #66
Opened 2021-04-20 11:59 UTC by furtivite

- Добавляет 404 страницу на виртуальном сервере ([инструкция](https://www.11ty.dev/docs/quicktips/not-found/#with-serve))

2021-04-20 13:09 UTC, pepelsbey requested changes

2021-04-20 13:09 UTC, pepelsbey commented on .eleventy.js
> +
Мне кажется, что лучше не усложнять локальный сервер обработкой 404 ошибок:

1. Можно всегда открыть адрес `/404` и проверить, как выглядит страница
2. Может сложиться впечатление, что этот конфиг отвечает за ответ удалённого сервера

2021-04-20 13:09 UTC, pepelsbey commented on netlify.toml
> +#     force = true
Комментарии лучше в исходниках не хранить

2021-04-20 13:09 UTC, pepelsbey commented on src/pages/404.njk
> +</div>
```suggestion
---

<h1>{{ title }}</h1>
<p><a href="/">Вернуться на главную</a></p>
```

Пока не свёрстано, лучше проще.

2021-04-20 13:30 UTC, furtivite commented on .eleventy.js
> +
Мне как раз кажется, что и локальный 404 будет удобен, например для случая, когда мы скачали доку для локального использования без интернета. Может тогда просто переименовать комментарий из `// 404` в `// 404 local only` ?

2021-04-20 13:45 UTC, pepelsbey commented on .eleventy.js
> +
Локальный 404 сработает только при запущенном сервере BrowserSync, он работает одинаково в офлайне и в онлайне. Я пока не понимаю, как это пригодится. Если мы всерьёз думаем про Доку в офлайне, то нужно сервис-воркер делать, а это другая история.

2021-04-20 13:48 UTC, furtivite commented on .eleventy.js
> +
Окей, уговорил, пусть такое локальное решение сохранится только в этом коммите.

2021-04-20 18:54 UTC, pepelsbey commented on .eleventy.js
> +const fs = require("fs")
```suggestion
```
Тогда и fs не нужен

2021-04-20 19:20 UTC, pepelsbey commented on src/pages/404.njk
> +</div>
Кхм, может всё же попроще? :)

2021-04-20 19:25 UTC, furtivite commented on src/pages/404.njk
> +</div>
А зачем? Заголовок у нас всегда `<h1>{{ title }}</h1>` - это и семантически верно, и передаётся он дополнительно в `<title>{{ title }} - Дока`

2021-04-20 19:54 UTC, pepelsbey commented on src/pages/404.njk
> +</div>
В твоём коде сейчас нет заголовка `<h1>`, то есть у страницы нет заголовка в контенте. Я его добавил :)

Ну и обёртка с неиспользуемым классом тоже пока не нужна. Не хотелось бы, чтобы будущий верстальщих вычищал лишнее.

2021-04-21 07:19 UTC, furtivite commented on src/pages/404.njk
> +</div>
Странно, я не заметил. Сорян.

2021-04-21 08:43 UTC, pepelsbey approved these changes

2021-04-21 08:45 UTC, merged